# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simion_optimizer.ui'
#
# Created: Tue Dec 13 12:55:30 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 923)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 0))
        Form.setMaximumSize(QtCore.QSize(770, 16777215))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.comboBox_iob = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_iob.sizePolicy().hasHeightForWidth())
        self.comboBox_iob.setSizePolicy(sizePolicy)
        self.comboBox_iob.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_iob.setObjectName("comboBox_iob")
        self.gridLayout.addWidget(self.comboBox_iob, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.comboBox_pa1 = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pa1.sizePolicy().hasHeightForWidth())
        self.comboBox_pa1.setSizePolicy(sizePolicy)
        self.comboBox_pa1.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_pa1.setObjectName("comboBox_pa1")
        self.gridLayout.addWidget(self.comboBox_pa1, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.comboBox_pa2 = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pa2.sizePolicy().hasHeightForWidth())
        self.comboBox_pa2.setSizePolicy(sizePolicy)
        self.comboBox_pa2.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_pa2.setObjectName("comboBox_pa2")
        self.gridLayout.addWidget(self.comboBox_pa2, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.comboBox_pa3 = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pa3.sizePolicy().hasHeightForWidth())
        self.comboBox_pa3.setSizePolicy(sizePolicy)
        self.comboBox_pa3.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_pa3.setObjectName("comboBox_pa3")
        self.gridLayout.addWidget(self.comboBox_pa3, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_20 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEdit_particles = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_particles.sizePolicy().hasHeightForWidth())
        self.lineEdit_particles.setSizePolicy(sizePolicy)
        self.lineEdit_particles.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_particles.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lineEdit_particles.setObjectName("lineEdit_particles")
        self.gridLayout_2.addWidget(self.lineEdit_particles, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        self.label_21.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.lineEdit_iterations = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_iterations.sizePolicy().hasHeightForWidth())
        self.lineEdit_iterations.setSizePolicy(sizePolicy)
        self.lineEdit_iterations.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_iterations.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lineEdit_iterations.setObjectName("lineEdit_iterations")
        self.gridLayout_2.addWidget(self.lineEdit_iterations, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_bad_news = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_bad_news.sizePolicy().hasHeightForWidth())
        self.lineEdit_bad_news.setSizePolicy(sizePolicy)
        self.lineEdit_bad_news.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_bad_news.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lineEdit_bad_news.setObjectName("lineEdit_bad_news")
        self.gridLayout_2.addWidget(self.lineEdit_bad_news, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setMaximumSize(QtCore.QSize(145, 16777215))
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 3, 0, 1, 1)
        self.lineEdit_trajectory_quality = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_trajectory_quality.sizePolicy().hasHeightForWidth())
        self.lineEdit_trajectory_quality.setSizePolicy(sizePolicy)
        self.lineEdit_trajectory_quality.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_trajectory_quality.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lineEdit_trajectory_quality.setObjectName("lineEdit_trajectory_quality")
        self.gridLayout_2.addWidget(self.lineEdit_trajectory_quality, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.line_14 = QtGui.QFrame(Form)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 1, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(750, 450))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(75, 20))
        self.label.setMaximumSize(QtCore.QSize(500, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_adj_elec_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_elec_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_elec_pa1.setSizePolicy(sizePolicy)
        self.textEdit_adj_elec_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_elec_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_elec_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_elec_pa1.setObjectName("textEdit_adj_elec_pa1")
        self.verticalLayout.addWidget(self.textEdit_adj_elec_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(75, 20))
        self.label_2.setMaximumSize(QtCore.QSize(500, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.textEdit_adj_volt_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_volt_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_volt_pa1.setSizePolicy(sizePolicy)
        self.textEdit_adj_volt_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_volt_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_volt_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_volt_pa1.setObjectName("textEdit_adj_volt_pa1")
        self.verticalLayout_2.addWidget(self.textEdit_adj_volt_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(75, 20))
        self.label_3.setMaximumSize(QtCore.QSize(500, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textEdit_v_min_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_min_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_v_min_pa1.setSizePolicy(sizePolicy)
        self.textEdit_v_min_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_min_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_min_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_min_pa1.setObjectName("textEdit_v_min_pa1")
        self.verticalLayout_3.addWidget(self.textEdit_v_min_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_26 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(75, 20))
        self.label_26.setMaximumSize(QtCore.QSize(500, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_16.addWidget(self.label_26)
        self.textEdit_v_max_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_max_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_v_max_pa1.setSizePolicy(sizePolicy)
        self.textEdit_v_max_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_max_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_max_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_max_pa1.setObjectName("textEdit_v_max_pa1")
        self.verticalLayout_16.addWidget(self.textEdit_v_max_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout_16)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(75, 20))
        self.label_4.setMaximumSize(QtCore.QSize(500, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textEdit_fix_elec_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_elec_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_elec_pa1.setSizePolicy(sizePolicy)
        self.textEdit_fix_elec_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_elec_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_elec_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_elec_pa1.setObjectName("textEdit_fix_elec_pa1")
        self.verticalLayout_4.addWidget(self.textEdit_fix_elec_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(75, 20))
        self.label_5.setMaximumSize(QtCore.QSize(500, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.textEdit_fix_volt_pa1 = QtGui.QTextEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_volt_pa1.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_volt_pa1.setSizePolicy(sizePolicy)
        self.textEdit_fix_volt_pa1.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_volt_pa1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_volt_pa1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_volt_pa1.setObjectName("textEdit_fix_volt_pa1")
        self.verticalLayout_5.addWidget(self.textEdit_fix_volt_pa1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(75, 20))
        self.label_6.setMaximumSize(QtCore.QSize(500, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.textEdit_adj_elec_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_elec_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_elec_pa2.setSizePolicy(sizePolicy)
        self.textEdit_adj_elec_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_elec_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_elec_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_elec_pa2.setObjectName("textEdit_adj_elec_pa2")
        self.verticalLayout_6.addWidget(self.textEdit_adj_elec_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(75, 20))
        self.label_7.setMaximumSize(QtCore.QSize(500, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.textEdit_adj_volt_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_volt_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_volt_pa2.setSizePolicy(sizePolicy)
        self.textEdit_adj_volt_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_volt_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_volt_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_volt_pa2.setObjectName("textEdit_adj_volt_pa2")
        self.verticalLayout_7.addWidget(self.textEdit_adj_volt_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.line_6 = QtGui.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(75, 20))
        self.label_8.setMaximumSize(QtCore.QSize(500, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.textEdit_v_min_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_min_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_v_min_pa2.setSizePolicy(sizePolicy)
        self.textEdit_v_min_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_min_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_min_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_min_pa2.setObjectName("textEdit_v_min_pa2")
        self.verticalLayout_8.addWidget(self.textEdit_v_min_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_27 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(75, 20))
        self.label_27.setMaximumSize(QtCore.QSize(500, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_17.addWidget(self.label_27)
        self.textEdit_v_max_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_max_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_v_max_pa2.setSizePolicy(sizePolicy)
        self.textEdit_v_max_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_max_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_max_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_max_pa2.setObjectName("textEdit_v_max_pa2")
        self.verticalLayout_17.addWidget(self.textEdit_v_max_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.line_7 = QtGui.QFrame(self.tab_2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.line_7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(75, 20))
        self.label_9.setMaximumSize(QtCore.QSize(500, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.textEdit_fix_elec_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_elec_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_elec_pa2.setSizePolicy(sizePolicy)
        self.textEdit_fix_elec_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_elec_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_elec_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_elec_pa2.setObjectName("textEdit_fix_elec_pa2")
        self.verticalLayout_9.addWidget(self.textEdit_fix_elec_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.line_8 = QtGui.QFrame(self.tab_2)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(75, 20))
        self.label_10.setMaximumSize(QtCore.QSize(500, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.textEdit_fix_volt_pa2 = QtGui.QTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_volt_pa2.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_volt_pa2.setSizePolicy(sizePolicy)
        self.textEdit_fix_volt_pa2.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_volt_pa2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_volt_pa2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_volt_pa2.setObjectName("textEdit_fix_volt_pa2")
        self.verticalLayout_10.addWidget(self.textEdit_fix_volt_pa2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(75, 20))
        self.label_11.setMaximumSize(QtCore.QSize(500, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.textEdit_adj_elec_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_elec_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_elec_pa3.setSizePolicy(sizePolicy)
        self.textEdit_adj_elec_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_elec_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_elec_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_elec_pa3.setObjectName("textEdit_adj_elec_pa3")
        self.verticalLayout_11.addWidget(self.textEdit_adj_elec_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.line_9 = QtGui.QFrame(self.tab_3)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_3.addWidget(self.line_9)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(75, 20))
        self.label_12.setMaximumSize(QtCore.QSize(500, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.textEdit_adj_volt_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_adj_volt_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_adj_volt_pa3.setSizePolicy(sizePolicy)
        self.textEdit_adj_volt_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_adj_volt_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_adj_volt_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_adj_volt_pa3.setObjectName("textEdit_adj_volt_pa3")
        self.verticalLayout_12.addWidget(self.textEdit_adj_volt_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.line_10 = QtGui.QFrame(self.tab_3)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_3.addWidget(self.line_10)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_28 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(75, 20))
        self.label_28.setMaximumSize(QtCore.QSize(500, 20))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_18.addWidget(self.label_28)
        self.textEdit_v_min_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_min_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_v_min_pa3.setSizePolicy(sizePolicy)
        self.textEdit_v_min_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_min_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_min_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_min_pa3.setObjectName("textEdit_v_min_pa3")
        self.verticalLayout_18.addWidget(self.textEdit_v_min_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(75, 20))
        self.label_13.setMaximumSize(QtCore.QSize(500, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.textEdit_v_max_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_v_max_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_v_max_pa3.setSizePolicy(sizePolicy)
        self.textEdit_v_max_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_v_max_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_v_max_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_v_max_pa3.setObjectName("textEdit_v_max_pa3")
        self.verticalLayout_13.addWidget(self.textEdit_v_max_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.line_11 = QtGui.QFrame(self.tab_3)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_3.addWidget(self.line_11)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(75, 20))
        self.label_14.setMaximumSize(QtCore.QSize(500, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.textEdit_fix_elec_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_elec_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_elec_pa3.setSizePolicy(sizePolicy)
        self.textEdit_fix_elec_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_elec_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_elec_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_elec_pa3.setObjectName("textEdit_fix_elec_pa3")
        self.verticalLayout_14.addWidget(self.textEdit_fix_elec_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.line_12 = QtGui.QFrame(self.tab_3)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_3.addWidget(self.line_12)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(75, 20))
        self.label_15.setMaximumSize(QtCore.QSize(500, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.textEdit_fix_volt_pa3 = QtGui.QTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_fix_volt_pa3.sizePolicy().hasHeightForWidth())
        self.textEdit_fix_volt_pa3.setSizePolicy(sizePolicy)
        self.textEdit_fix_volt_pa3.setMinimumSize(QtCore.QSize(75, 250))
        self.textEdit_fix_volt_pa3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit_fix_volt_pa3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_fix_volt_pa3.setObjectName("textEdit_fix_volt_pa3")
        self.verticalLayout_15.addWidget(self.textEdit_fix_volt_pa3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 0, 1, 1)
        self.lineEdit_leader1 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_leader1.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_leader1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_leader1.setObjectName("lineEdit_leader1")
        self.gridLayout_3.addWidget(self.lineEdit_leader1, 0, 1, 1, 1)
        self.lineEdit_leader2 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_leader2.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_leader2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_leader2.setObjectName("lineEdit_leader2")
        self.gridLayout_3.addWidget(self.lineEdit_leader2, 0, 2, 1, 1)
        self.lineEdit_leader3 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_leader3.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_leader3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_leader3.setObjectName("lineEdit_leader3")
        self.gridLayout_3.addWidget(self.lineEdit_leader3, 0, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 0, 1, 1)
        self.textEdit_disciples1 = QtGui.QTextEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_disciples1.sizePolicy().hasHeightForWidth())
        self.textEdit_disciples1.setSizePolicy(sizePolicy)
        self.textEdit_disciples1.setMinimumSize(QtCore.QSize(70, 200))
        self.textEdit_disciples1.setMaximumSize(QtCore.QSize(80, 250))
        self.textEdit_disciples1.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_disciples1.setObjectName("textEdit_disciples1")
        self.gridLayout_3.addWidget(self.textEdit_disciples1, 1, 1, 1, 1)
        self.textEdit_disciples2 = QtGui.QTextEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_disciples2.sizePolicy().hasHeightForWidth())
        self.textEdit_disciples2.setSizePolicy(sizePolicy)
        self.textEdit_disciples2.setMinimumSize(QtCore.QSize(70, 250))
        self.textEdit_disciples2.setMaximumSize(QtCore.QSize(80, 250))
        self.textEdit_disciples2.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_disciples2.setObjectName("textEdit_disciples2")
        self.gridLayout_3.addWidget(self.textEdit_disciples2, 1, 2, 1, 1)
        self.textEdit_disciples3 = QtGui.QTextEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_disciples3.sizePolicy().hasHeightForWidth())
        self.textEdit_disciples3.setSizePolicy(sizePolicy)
        self.textEdit_disciples3.setMinimumSize(QtCore.QSize(70, 250))
        self.textEdit_disciples3.setMaximumSize(QtCore.QSize(80, 250))
        self.textEdit_disciples3.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_disciples3.setObjectName("textEdit_disciples3")
        self.gridLayout_3.addWidget(self.textEdit_disciples3, 1, 3, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(76, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_29 = QtGui.QLabel(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(75, 20))
        self.label_29.setMaximumSize(QtCore.QSize(500, 20))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_19.addWidget(self.label_29)
        self.textEdit_g = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_g.sizePolicy().hasHeightForWidth())
        self.textEdit_g.setSizePolicy(sizePolicy)
        self.textEdit_g.setMinimumSize(QtCore.QSize(20, 250))
        self.textEdit_g.setMaximumSize(QtCore.QSize(75, 16777215))
        self.textEdit_g.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_g.setObjectName("textEdit_g")
        self.verticalLayout_19.addWidget(self.textEdit_g)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.line_13 = QtGui.QFrame(self.tab_5)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_10.addWidget(self.line_13)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_30 = QtGui.QLabel(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(20, 20))
        self.label_30.setMaximumSize(QtCore.QSize(75, 20))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_20.addWidget(self.label_30)
        self.textEdit_g_min = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_g_min.sizePolicy().hasHeightForWidth())
        self.textEdit_g_min.setSizePolicy(sizePolicy)
        self.textEdit_g_min.setMinimumSize(QtCore.QSize(20, 250))
        self.textEdit_g_min.setMaximumSize(QtCore.QSize(75, 16777215))
        self.textEdit_g_min.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_g_min.setObjectName("textEdit_g_min")
        self.verticalLayout_20.addWidget(self.textEdit_g_min)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.line_17 = QtGui.QFrame(self.tab_5)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_10.addWidget(self.line_17)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_31 = QtGui.QLabel(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(20, 20))
        self.label_31.setMaximumSize(QtCore.QSize(75, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_21.addWidget(self.label_31)
        self.textEdit_g_max = QtGui.QTextEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_g_max.sizePolicy().hasHeightForWidth())
        self.textEdit_g_max.setSizePolicy(sizePolicy)
        self.textEdit_g_max.setMinimumSize(QtCore.QSize(20, 250))
        self.textEdit_g_max.setMaximumSize(QtCore.QSize(75, 16777215))
        self.textEdit_g_max.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_g_max.setObjectName("textEdit_g_max")
        self.verticalLayout_21.addWidget(self.textEdit_g_max)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 0, 0, 2, 1)
        spacerItem1 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_32 = QtGui.QLabel(self.tab_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_nr_of_g_particles = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_nr_of_g_particles.setObjectName("lineEdit_nr_of_g_particles")
        self.gridLayout_4.addWidget(self.lineEdit_nr_of_g_particles, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 1, 0, 1, 1)
        self.lineEdit_nr_of_g_iterations = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_nr_of_g_iterations.setObjectName("lineEdit_nr_of_g_iterations")
        self.gridLayout_4.addWidget(self.lineEdit_nr_of_g_iterations, 1, 1, 1, 1)
        self.pushButton_load_gemfile = QtGui.QPushButton(self.tab_5)
        self.pushButton_load_gemfile.setObjectName("pushButton_load_gemfile")
        self.gridLayout_4.addWidget(self.pushButton_load_gemfile, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_6.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.line_15 = QtGui.QFrame(Form)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 3, 0, 1, 2)
        self.qwtPlot = Plot(Form)
        self.qwtPlot.setMaximumSize(QtCore.QSize(950, 16777215))
        self.qwtPlot.setObjectName("qwtPlot")
        self.gridLayout_6.addWidget(self.qwtPlot, 4, 0, 1, 2)
        self.line_16 = QtGui.QFrame(Form)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_6.addWidget(self.line_16, 5, 0, 1, 2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_voltage_only = QtGui.QCheckBox(Form)
        self.checkBox_voltage_only.setChecked(True)
        self.checkBox_voltage_only.setObjectName("checkBox_voltage_only")
        self.horizontalLayout_9.addWidget(self.checkBox_voltage_only)
        spacerItem3 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.pushButton_stop = QtGui.QPushButton(Form)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_9.addWidget(self.pushButton_stop)
        self.pushButton_start = QtGui.QPushButton(Form)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_9.addWidget(self.pushButton_start)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 6, 0, 1, 2)
        self.horizontalLayout_11.addLayout(self.gridLayout_6)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "iob File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "PA# 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "PA# 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "PA# 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "number of particles", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_particles.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "number of iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_iterations.setText(QtGui.QApplication.translate("Form", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "number of bad news", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bad_news.setText(QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "trajectory quality", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_trajectory_quality.setText(QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "adj elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_elec_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "adj volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_volt_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "v min", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_min_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-200</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-200</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "v max", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_max_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "fix elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_elec_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "fix volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_volt_pa1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-70</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "PA 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "adj elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_elec_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "adj volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_volt_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "v min", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_min_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "v max", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_max_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "fix elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_elec_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "fix volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_volt_pa2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "PA 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "adj elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_elec_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "adj volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_adj_volt_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "v min", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_min_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "v max", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_v_max_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "fix elec", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_elec_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "fix volt", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_fix_volt_pa3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "PA 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Leader Electrode Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Disciple Electrodes</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> Indices</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_disciples1.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_disciples2.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_disciples3.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Shared Voltages", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "Geom Param", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_g.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "G min", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_g_min.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">100</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">300</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "G max", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_g_max.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-100</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-200</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-300</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "Nr of geom Particles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Nr of geom Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_load_gemfile.setText(QtGui.QApplication.translate("Form", "load geometry File", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_voltage_only.setText(QtGui.QApplication.translate("Form", "Use Voltage optimization only", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("Form", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("Form", "START", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.Qwt5.qplt import Plot
