#file created by simion optimizer
def create_gemfile(G):
    file=open('/home/hs/ftp/example.gem','w')
    file.write('pa_define(100,50,1,c,y,,)\n')
    file.write('\n')
    file.write('locate(0,0,0,1,0,0,0)\n')
    file.write('{\n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('; ELECTRODE \n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('electrode(1)\n')
    file.write('    {\n')
    file.write('    fill\n')
    file.write('        {\n')
    file.write('        within{box(20,%i,30,50)}\n' %G[0])
    file.write('        }\n')
    file.write('    }\n')
    file.write('\n')
    file.write('\n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('; ELECTRODE \n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('electrode(2)\n')
    file.write('    {\n')
    file.write('    fill\n')
    file.write('        {\n')
    file.write('        within{box(60,%i,70,50)}\n' %G[1])
    file.write('        }\n')
    file.write('    }\n')
    file.write('        \n')
    file.write('    \n')
    file.write('\n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('; ELECTRODE \n')
    file.write(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n')
    file.write('electrode(3)\n')
    file.write('    {\n')
    file.write('    fill\n')
    file.write('        {\n')
    file.write('        within{box(80,0,100,50)}\n')
    file.write('        }\n')
    file.write('    }\n')
    file.write('\n')
    file.write('}\n')
    file.write('        \n')
    file.write('    \n')
    file.write('\n')
    file.close()
